graphhopper:
  datareader.file: osm.pbf
  graph.location: graphs/brandenburg-with-transit

  profiles:
    - name: car
      vehicle: car
      weighting: fastest
      turn_costs: true

server:
  application_connectors:
    - type: http
      port: 8989
      bind_host: localhost
  admin_connectors:
    - type: http
      port: 8990
      bind_host: localhost
